name: Build and Deploy
on:
  push:
    branches:
      - test
    paths:
      - 'entities/**'


jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Create PR to branch
        run: ./push-create-pr.sh
