name: Build and Deploy
on:
  push:
    branches:
      - test
    paths:
      - 'entities/**'


jobs:
  cherry_pick_release_v2_0:
    runs-on: ubuntu-latest
    name: Cherry pick into docs-workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into docs-workflow
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: docs-workflow
          labels: |
            cherry-pick
          reviewers: |
            parthp2107
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
