name: Build and Deploy
on:
  push:
    branches:
      - 0.6.0
    paths:
      - 'docs/**'

jobs:
  cherry_pick_release_v2_0:
    runs-on: ubuntu-latest
    name: Cherry pick into release-v2.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into release-v2.0
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: docs-workflow
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
