name: Build and Deploy
on:
  push:
    branches:
      - test
    paths:
      - 'entities/**'

jobs:
  cherry_pick_release_v2_0:
    runs-on: ubuntu-latest
    name: Cherry pick into release-v2.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into release-v2.0
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
